version: '3.7'
services:
  db:
    image: postgres
    env_file: .env
    logging:
      driver: none

  backend:
    build: ./backend
    env_file: .env
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - backend
    logging:
      driver: none
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro