# Generated by Django 3.0.2 on 2020-01-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4')),
                ('timestamp', models.DateTimeField()),
                ('http_method', models.PositiveSmallIntegerField(choices=[(1, 'Get'), (2, 'Head'), (3, 'Post'), (4, 'Put'), (5, 'Delete'), (6, 'Connect'), (7, 'Options'), (8, 'Trace'), (9, 'Patch')])),
                ('uri', models.TextField()),
                ('status_code', models.PositiveSmallIntegerField()),
                ('content_length', models.PositiveIntegerField()),
                ('user_agent', models.TextField()),
                ('referer', models.TextField()),
            ],
            options={
                'db_table': 'logs',
            },
        ),
    ]
